# -*- coding: utf-8 -*-
"""Train_Phase_On_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTdAo5Dh-3KTL7tAioI3ZdP5tkuJG3Bp
"""

!pip install ultralytics==8.2.103 -q

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.info()
# Train the model

from google.colab import drive
drive.mount('/content/drive')

train_results = model.train(
    data="/content/drive/MyDrive/Yolo/data/data.yaml",                     # Path to your dataset YAML
    epochs=500,                           # Total training epochs
    batch=16,                                           # Image size
    device="cuda",
    save_period = 20
)

import shutil
import os
save_dir = "/content/drive/MyDrive/YOLO_Checkpoints"
weights_dir = "/content/runs/detect/train/weights"
shutil.copy(os.path.join(weights_dir, "last.pt"), save_dir)
shutil.copy(os.path.join(weights_dir, "best.pt"), save_dir)

save_dir = "/content/drive/MyDrive/final_model"
os.makedirs(save_dir, exist_ok=True)
model_path = os.path.join(save_dir, "final_model.pt")
model = model.save(model_path)

from google.colab import drive
drive.mount('/content/drive')

import shutil
import os
save_dir = '/content/drive/MyDrive/YOLO_Runs'
os.makedirs(save_dir, exist_ok=True)

# Copy the results to Google Drive
shutil.copytree("/content/runs", save_dir, dirs_exist_ok=True)
print(f"Training results saved to {save_dir}")

# import shutil
# import os
# if os.path.exists("/content/runs"):
#     shutil.rmtree("/content/runs")
#     print("Cleaned runs directory.")

train_results